export const transactions = [
    {
      id: 1,
      category: 'Еда',
      amount: 50,
      date: '2024-05-12',
      description: 'Супермаркет',
      type: 'expense',
    },
    {
      id: 2,
      category: 'Зарплата',
      amount: 2000,
      date: '2024-05-10',
      type: 'income',
    },
    {
      id: 3,
      category: 'Транспорт',
      amount: 30,
      date: '2024-05-11',
      description: 'Проездной',
      type: 'expense',
    },
    {
      id: 4,
      category: 'Еда',
      amount: 25,
      date: '2024-05-13',
      description: 'Кафе',
      type: 'expense',
    },
    {
      id: 5,
      category: 'Развлечения',
      amount: 60,
      date: '2024-05-14',
      description: 'Кино',
      type: 'expense',
    },
    {
      id: 6,
      category: 'Здоровье',
      amount: 150,
      date: '2024-05-06',
      description: 'Аптека',
      type: 'expense',
    },
    {
      id: 7,
      category: 'Еда',
      amount: 80,
      date: '2024-05-15',
      description: 'Ресторан',
      type: 'expense',
    },
    {
      id: 8,
      category: 'Зарплата',
      amount: 2100,
      date: '2024-04-30',
      type: 'income',
    },
    {
      id: 9,
      category: 'Транспорт',
      amount: 20,
      date: '2024-05-16',
      description: 'Такси',
      type: 'expense',
    },
    {
      id: 10,
      category: 'Развлечения',
      amount: 45,
      date: '2024-05-08',
      description: 'Концерт',
      type: 'expense',
    },
    {
      id: 11,
      category: 'Здоровье',
      amount: 200,
      date: '2024-05-03',
      description: 'Стоматолог',
      type: 'expense',
    },
  ];
  